### ISSUE TITLE
Character Arrays and Structs

### ISSUE THREAD

**Issue by kaendfinger** [mezoni/binary_interop#11]
I'm trying to add uname support for syscall, but I am running into this issue:

In my header:
```c
struct utsname {
  char nodename[];
  char release[];
  char version[];
  char machine[];
  char sysname[];
};
```

When I try to load the header:

```
➜ SystemCalls git:(master) ✗ dart example/uname.dart
Unhandled exception:
BinaryType error: Declaration 'struct utsname { char nodename[]; char release[]; char version[]; char machine[]; char sysname[]; }' has error: BinaryType error: Flexible array member 'nodename' not at end of struct 'struct utsname'
#0      BinaryTypeError.flexibleArrayMemberNotAtEndOfStruct (package:binary_types/src/errors.dart:35:5)
#1      StorageUnits._normalizeMembers (package:binary_types/src/storage_units.dart:312:29)
#2      StorageUnits.StorageUnits (package:binary_types/src/storage_units.dart:81:15)
#3      StructureType.addMembers (package:binary_types/src/structures.dart:276:25)
#4      _Declarations._resolveStructure (package:binary_types/src/declarations.dart:545:20)
#5      _Declarations._declareStructure (package:binary_types/src/declarations.dart:268:5)
#6      _Declarations.declare (package:binary_types/src/declarations.dart:41:11)
#7      BinaryTypeHelper.declare (package:binary_types/src/type_helper.dart:126:24)
#8      LibC.load (package:syscall/src/core.dart:266:16)
#9      _ensure (package:syscall/src/core.dart:214:10)
#10     alloc (package:syscall/src/core.dart:312:3)
#11     getKernelInfo (package:syscall/src/system.dart:528:11)
#12     main (file:///Users/alex/DirectCode/SystemCalls/example/uname.dart:4:14)
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

#0      BinaryTypeError.declarationError (package:binary_types/src/errors.dart:19:5)
#1      _Declarations.declare (package:binary_types/src/declarations.dart:51:23)
#2      BinaryTypeHelper.declare (package:binary_types/src/type_helper.dart:126:24)
#3      LibC.load (package:syscall/src/core.dart:266:16)
#4      _ensure (package:syscall/src/core.dart:214:10)
#5      alloc (package:syscall/src/core.dart:312:3)
#6      getKernelInfo (package:syscall/src/system.dart:528:11)
#7      main (file:///Users/alex/DirectCode/SystemCalls/example/uname.dart:4:14)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

Any way to get around this?

**Comment by mezoni** [comment]
From wikipedia

Flexible array member[1] is a feature introduced in the C99 standard of the C programming language (in particular, in section §6.7.2.1, item 16, page 103).[2] It is a member of a struct, which is an array without a given dimension, and it should be the last member of such a struct, as in the following example:

```c
struct double_vector_st {
    unsigned length;
    double array[]; // the flexible array member should be last
};
```

You try to declare 5! flexible array!
This is not allowed in C language.

**Comment by kaendfinger** [comment]
@mezoni I see now xD Thanks

**Comment by mezoni** [comment]
I found the following implementation:

```c
/* Structure describing the system and machine.  */
struct utsname
  {
    /* Name of the implementation of the operating system.  */
    char sysname[_UTSNAME_LENGTH];

    /* Name of this node on the network.  */
    char nodename[_UTSNAME_NODENAME_LENGTH];

    /* Current release level of this implementation.  */
    char release[_UTSNAME_LENGTH];
    /* Current version level of this release.  */
    char version[_UTSNAME_LENGTH];

    /* Name of the hardware type the system is running on.  */
    char machine[_UTSNAME_LENGTH];

#if _UTSNAME_DOMAIN_LENGTH - 0
    /* Name of the domain of this node on the network.  */
# ifdef __USE_GNU
    char domainname[_UTSNAME_DOMAIN_LENGTH];
# else
    char __domainname[_UTSNAME_DOMAIN_LENGTH];
# endif
#endif
  };
```
