### ISSUE TITLE
Issue with latest update

### ISSUE THREAD

**Issue by kaendfinger** [mezoni/binary_interop#13]
I have a major issue with the latest update:

```
➜ SystemCalls git:(master) ✗ dart example/readline.dart
$ ls
Unhandled exception:
Uncaught Error: Invalid argument(s): Function 'ffi_call' already resolved
Stack Trace:
#0      LibffiExtension._resolveFunction (package:libffi6_extension/src/ffi6_extension.dart:188:86)
#1      LibffiExtension.resolveFunction (package:libffi6_extension/src/ffi6_extension.dart:165:5)
#2      LibffiLibrary._resolveFunction (package:libffi6_support/src/libffi_library/libffi_library.dart:79:21)
#3      LibffiLibrary.LibffiLibrary (package:libffi6_support/src/libffi_library/libffi_library.dart:22:5)
#4      LibffiLibrary._load (package:libffi6_support/src/libffi_library/libffi_library.dart:169:16)
#5      LibffiLibrary.current (package:libffi6_support/src/libffi_library/libffi_library.dart:6:40)
#6      LibffiLibrary.current (package:libffi6_support/src/libffi_library/libffi_library.dart:6:30)
#7      ForeignFunction.ForeignFunction (package:libffi6_support/src/libffi_support/foreign_function.dart:55:23)
#8      DynamicLibrary._compile (package:binary_interop/dynamic_library/src/dynamic_library.dart:427:24)
#9      DynamicLibrary.invokeEx (package:binary_interop/dynamic_library/src/dynamic_library.dart:349:18)
#10     LibraryManager.invoke (package:syscall/src/core.dart:307:16)
#11     invoke (package:syscall/src/core.dart:450:25)
#12     LibReadline.init (package:syscall/readline.dart:42:24)
#13     Readline.addLineToHistory (package:syscall/readline.dart:65:17)
#14     handleLine.<handleLine_async_body> (file:///Users/alex/DirectCode/SystemCalls/example/readline.dart:53:12)
#15     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#17     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

This is due to me using binary_interop in multiple isolates. Can we somehow use like thread locals or something to make this not happen?

See https://github.com/DirectMyFile/syscall/blob/master/example/readline.dart

@mezoni

**Comment by kaendfinger** [comment]
@mezoni The code is up-to-date in my syscall library.

**Comment by kaendfinger** [comment]
@mezoni Found the issue. It's called: Using multiple isolates.

**Comment by mezoni** [comment]
This means that the native extensions are shared between the isolates.
I will fix this.
I don't know about that but now know.

**Comment by kaendfinger** [comment]
@mezoni :) Also, your binary callbacks work VERY well! Thanks for this! Readline library is almost ready for production :P

**Comment by mezoni** [comment]
Fixed in `libffi6_extension`.
Need recompile on Mac OS.

**Comment by kaendfinger** [comment]
Ok, sounds good.
