### ISSUE TITLE
ARM Error

### ISSUE THREAD

**Issue by kaendfinger** [mezoni/binary_interop#8]
Error with running binary interop on ARM. Working on a fix.

```
pi@raspberrypi ~/Code/syscall $ dart example/fork.dart
Unhandled exception:
Unsupported operation: Unsupported binary interface: null
#0      DynamicLibrary.load (package:binary_interop/dynamic_library/src/dynamic_library.dart:478:7)
#1      LibC.load (package:syscall/src/core.dart:219:28)
#2      LibC.libc (package:syscall/src/core.dart:203:7)
#3      LibC.invoke (package:syscall/src/core.dart:238:12)
#4      invoke (package:syscall/src/core.dart:371:15)
#5      getProcessId (package:syscall/src/system.dart:318:10)
#6      main (file:///home/pi/Code/syscall/example/fork.dart:4:25)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:255)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:142)
```

**Comment by mezoni** [comment]
OK. I will look.

**Comment by kaendfinger** [comment]
I've got it.

**Comment by kaendfinger** [comment]
See #9
